### ISSUE TITLE
Validator complains about TR_m4_varos not using unique head/hair

### ISSUE THREAD

**Issue by MortimerMcMire** [TD-Addon/StandardsValidator#1]
but we aren't using those anymore, this error can be safely ignored

**Comment by Assumeru** [comment]
0b7f9f7d814af1c942d6ff62374193f1458b73f1 silences the warning about TR_m4_varos not using his assigned head. NPCs with an id other than `UNUSED TR_m4_varos` using this head will still result in a warning.
