### ISSUE TITLE
Bloodmoon paralysis weapons and Tribunal goblin weapons should be added to the uniques list

### ISSUE THREAD

**Issue by RonikTR** [TD-Addon/StandardsValidator#4]
They aren't unique, but due to their bonkers stats they shouldn't be placed anywhere in PTR, and in the past we've made efforts to replace them with more balanced alternatives.

IDs:

- silver staff of paralysis
- silver axe of paralysis
- silver sword of paralysis
- goblin_sword
- goblin_club

**Comment by Assumeru** [comment]
I'm inclined to say the silver weapons might be okay on some high level enemies... but it's definitely better to report them.
